# Generated by Django 5.2.11 on 2026-02-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_product_name_en_product_name_ru_product_name_uz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('name_uz', models.CharField(max_length=127, null=True)),
                ('name_en', models.CharField(max_length=127, null=True)),
                ('name_ru', models.CharField(max_length=127, null=True)),
                ('content', models.CharField(max_length=127)),
                ('content_uz', models.CharField(max_length=127, null=True)),
                ('content_en', models.CharField(max_length=127, null=True)),
                ('content_ru', models.CharField(max_length=127, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
